In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('customers-100.csv')

In [10]:
df1 = df.dropna()
df1.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
7,8.0,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,12-04-2021,https://hammond-ramsey.com/
8,9.0,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,13-01-2020,https://www.bullock.net/
9,10.0,8C2811a503C7c5a,Michelle,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,08-11-2021,https://arias.com/
10,11.0,216E205d6eBb815,Carl,Schroeder,"Oconnell, Meza and Everett",Shannonville,Guernsey,637-854-0256x825,114.336.0784x788,kirksalas@webb.com,20-10-2021,https://simmons-hurley.com/
11,12.0,CEDec94deE6d69B,Jenna,Dodson,"Hoffman, Reed and Mcclain",East Andrea,Vietnam,(041)737-3846,+1-556-888-3485x42608,mark42@robbins.com,29-11-2020,http://www.douglas.net/

In [12]:
df2 = df.dropna(how="all")
df2.head(10)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,NaN,Chile,NaN,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,beckycarr@hogan.com,NaN,NaN
4,5.0,053d585Ab6b3159,Joanna,NaN,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(283)437-3886x88321,999-728-1637,NaN,NaN,NaN
6,7.0,EA4d384DfDbBf77,Darren,NaN,"Lester, Woodard and Mitchell",Lake Ana,NaN,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,24-08-2021,https://www.le.com/
7,8.0,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,12-04-2021,https://hammond-ramsey.com/
8,9.0,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,13-01-2020,https://www.bullock.net/
9,10.0,8C2811a503C7c5a,Michelle,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,08-11-2021,https://arias.com/
10,11.0,216E205d6eBb815,Carl,Schroeder,"Oconnell, Meza and Everett",Shannonville,Guernsey,637-854-0256x825,114.336.0784x788,kirksalas@webb.com,20-10-2021,https://simmons-hurley.com/

In [16]:
df3 = df.dropna(thresh=2)
df3.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,NaN,Chile,NaN,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
4,5.0,053d585Ab6b3159,Joanna,NaN,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(283)437-3886x88321,999-728-1637,NaN,NaN,NaN
6,7.0,EA4d384DfDbBf77,Darren,NaN,"Lester, Woodard and Mitchell",Lake Ana,NaN,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,24-08-2021,https://www.le.com/

In [17]:
df1 = df.replace('Chile', 'CH')
df1.head(2)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,NaN,CH,NaN,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/

In [18]:
df3 = df.replace({
    "First Name": "Sheryl",
    "Country": "Chile"}, "Hello")
df3.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,Hello,Baxter,Rasmussen Group,NaN,Hello,NaN,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,beckycarr@hogan.com,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,053d585Ab6b3159,Joanna,NaN,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/

In [19]:
import numpy as np

In [20]:
df2 = df.replace('Chile', np.nan)
df2.head(2)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,NaN,NaN,NaN,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/

In [21]:
df3 = df.replace(["Chile", "Sheryl","Preston"], "New Value")
df3.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,New Value,Baxter,Rasmussen Group,NaN,New Value,NaN,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,New Value,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,beckycarr@hogan.com,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,053d585Ab6b3159,Joanna,NaN,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/

In [22]:
df3 = df.replace({
    "Baxter": "No Surname",
    "053d585Ab6b3159": "No Id"})
df3.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,Sheryl,No Surname,Rasmussen Group,NaN,Chile,NaN,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,Preston,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,beckycarr@hogan.com,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,No Id,Joanna,NaN,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/

In [23]:
df3 = df.replace({'First Name': '[A-Za-z]'}, " ",
					regex= True)
df3.head(10)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,,Baxter,Rasmussen Group,NaN,Chile,NaN,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,beckycarr@hogan.com,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,053d585Ab6b3159,,NaN,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(283)437-3886x88321,999-728-1637,NaN,NaN,NaN
6,7.0,EA4d384DfDbBf77,,NaN,"Lester, Woodard and Mitchell",Lake Ana,NaN,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,24-08-2021,https://www.le.com/
7,8.0,0e04AFde9f225dE,,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,12-04-2021,https://hammond-ramsey.com/
8,9.0,C2dE4dEEc489ae0,,Meyers,Browning-Simon,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,13-01-2020,https://www.bullock.net/
9,10.0,8C2811a503C7c5a,,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,08-11-2021,https://arias.com/

In [24]:
df3 = df.replace(["Chile", "Sheryl","Preston"], [1,2,3])
df3.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1.0,DD37Cf93aecA6Dc,2,Baxter,Rasmussen Group,NaN,1,NaN,397.884.0519x718,zunigavanessa@smith.info,24-08-2020,http://www.stephenson.com/
1,2.0,1Ef7b82A4CAAD10,3,Lozano,NaN,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,23-04-2021,http://www.hobbs.com/
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,beckycarr@hogan.com,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,053d585Ab6b3159,Joanna,NaN,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,17-04-2021,https://goodwin-ingram.com/

# Group By

In [25]:
df = pd.DataFrame({
    "City": ['Mumbai','Mumbai','Mumbai', 'Bhubaneswar', 'Bhubaneswar', 'Bhubaneswar', 'Bengaluru','Bengaluru','Bengaluru'],
    "temp": [12,13,19,41,31,40,38,29,40],
    "wind": [5,6,23,5,8,9,1,9,6]})
df

          City  temp  wind
0       Mumbai    12     5
1       Mumbai    13     6
2       Mumbai    19    23
3  Bhubaneswar    41     5
4  Bhubaneswar    31     8
5  Bhubaneswar    40     9
6    Bengaluru    38     1
7    Bengaluru    29     9
8    Bengaluru    40     6

In [26]:
gr = df.groupby('City')
gr

In [27]:
for city, cityDf in gr:
    print(city)
    print(cityDf)

Bengaluru
        City  temp  wind
6  Bengaluru    38     1
7  Bengaluru    29     9
8  Bengaluru    40     6
Bhubaneswar
          City  temp  wind
3  Bhubaneswar    41     5
4  Bhubaneswar    31     8
5  Bhubaneswar    40     9
Mumbai
     City  temp  wind
0  Mumbai    12     5
1  Mumbai    13     6
2  Mumbai    19    23

In [28]:
gr.get_group("Bhubaneswar")

          City  temp  wind
3  Bhubaneswar    41     5
4  Bhubaneswar    31     8
5  Bhubaneswar    40     9

In [29]:
gr.max()

             temp  wind
City
Bengaluru      40     9
Bhubaneswar    41     9
Mumbai         19    23

In [30]:
gr.min()

             temp  wind
City
Bengaluru      29     1
Bhubaneswar    31     5
Mumbai         12     5

In [31]:
gr.mean()

                  temp       wind
City
Bengaluru    35.666667   5.333333
Bhubaneswar  37.333333   7.333333
Mumbai       14.666667  11.333333

In [32]:
gr.describe()

             temp                                                     wind  \
            count       mean       std   min   25%   50%   75%   max count
City
Bengaluru     3.0  35.666667  5.859465  29.0  33.5  38.0  39.0  40.0   3.0
Bhubaneswar   3.0  37.333333  5.507571  31.0  35.5  40.0  40.5  41.0   3.0
Mumbai        3.0  14.666667  3.785939  12.0  12.5  13.0  16.0  19.0   3.0


                  mean        std  min  25%  50%   75%   max
City
Bengaluru     5.333333   4.041452  1.0  3.5  6.0   7.5   9.0
Bhubaneswar   7.333333   2.081666  5.0  6.5  8.0   8.5   9.0
Mumbai       11.333333  10.115994  5.0  5.5  6.0  14.5  23.0

In [33]:
gr1 = df.groupby('wind')

In [34]:
for speed, group in gr1:
    print(speed)
    print(group)

1
        City  temp  wind
6  Bengaluru    38     1
5
          City  temp  wind
0       Mumbai    12     5
3  Bhubaneswar    41     5
6
        City  temp  wind
1     Mumbai    13     6
8  Bengaluru    40     6
8
          City  temp  wind
4  Bhubaneswar    31     8
9
          City  temp  wind
5  Bhubaneswar    40     9
7    Bengaluru    29     9
23
     City  temp  wind
2  Mumbai    19    23

In [35]:
weather1 = pd.DataFrame({
    "City": ['Mumbai', 'Bhubaneswar','Bengaluru'],
    "temp": [12,13,19],
    "wind": [5,6,23]})
weather1

          City  temp  wind
0       Mumbai    12     5
1  Bhubaneswar    13     6
2    Bengaluru    19    23

In [36]:
weather2 = pd.DataFrame({
    "City": ['Chennai', 'Delhi','Hyderabad'],
    "temp": [23,23,29],
    "wind": [5,6,9]})
weather2

        City  temp  wind
0    Chennai    23     5
1      Delhi    23     6
2  Hyderabad    29     9

In [37]:
df = pd.concat([weather1, weather2])
df

          City  temp  wind
0       Mumbai    12     5
1  Bhubaneswar    13     6
2    Bengaluru    19    23
0      Chennai    23     5
1        Delhi    23     6
2    Hyderabad    29     9

In [38]:
df = pd.concat([weather1, weather2], ignore_index=True)
df

          City  temp  wind
0       Mumbai    12     5
1  Bhubaneswar    13     6
2    Bengaluru    19    23
3      Chennai    23     5
4        Delhi    23     6
5    Hyderabad    29     9

In [39]:
df = pd.concat([weather1, weather2], keys=["DF1", "DF2"])
df

              City  temp  wind
DF1 0       Mumbai    12     5
    1  Bhubaneswar    13     6
    2    Bengaluru    19    23
DF2 0      Chennai    23     5
    1        Delhi    23     6
    2    Hyderabad    29     9

In [40]:
df.loc['DF2']

        City  temp  wind
0    Chennai    23     5
1      Delhi    23     6
2  Hyderabad    29     9

In [41]:
df = pd.concat([weather1, weather2], axis= 1)
df

          City  temp  wind       City  temp  wind
0       Mumbai    12     5    Chennai    23     5
1  Bhubaneswar    13     6      Delhi    23     6
2    Bengaluru    19    23  Hyderabad    29     9

In [42]:
df = pd.concat([weather1, weather2], axis= 0)
df

          City  temp  wind
0       Mumbai    12     5
1  Bhubaneswar    13     6
2    Bengaluru    19    23
0      Chennai    23     5
1        Delhi    23     6
2    Hyderabad    29     9

In [43]:
df1 = pd.DataFrame({
    "City": ['Mumbai', 'Bhubaneswar','Bengaluru'],
    "temp": [12,13,19],
    "wind": [5,6,23]}, index = [1,2,3])
df1

          City  temp  wind
1       Mumbai    12     5
2  Bhubaneswar    13     6
3    Bengaluru    19    23

In [44]:
df2 = pd.DataFrame({
    "City": ['Mumbai', 'Bhubaneswar','Bengaluru'],
    "temp": [12,13,19],
    "wind": [5,6,23]}, index = [2,1,3])
df2

          City  temp  wind
2       Mumbai    12     5
1  Bhubaneswar    13     6
3    Bengaluru    19    23