In [1]:
import pandas as pd

In [2]:
temp = pd.DataFrame({
    "City": ['Mumbai', 'Bhubaneswar','Bengaluru', 'Kolkata'],
    "temp": [12,13,19, 30]})
temp

          City  temp
0       Mumbai    12
1  Bhubaneswar    13
2    Bengaluru    19
3      Kolkata    30

In [3]:
wind = pd.DataFrame({
    "City": ['Mumbai', 'Bhubaneswar','Delhi'],
    "wind": [5,6,23]})
wind

          City  wind
0       Mumbai     5
1  Bhubaneswar     6
2        Delhi    23

In [4]:
df = pd.merge(temp, wind, on='City')
df

          City  temp  wind
0       Mumbai    12     5
1  Bhubaneswar    13     6

In [5]:
df = pd.merge(temp, wind, on='City', how="left")
df

          City  temp  wind
0       Mumbai    12   5.0
1  Bhubaneswar    13   6.0
2    Bengaluru    19   NaN
3      Kolkata    30   NaN

In [6]:
df = pd.merge(temp, wind, on='City', how="right")
df

          City  temp  wind
0       Mumbai  12.0     5
1  Bhubaneswar  13.0     6
2        Delhi   NaN    23

In [7]:
df = pd.merge(temp, wind, on='City', how="outer")
df

          City  temp  wind
0    Bengaluru  19.0   NaN
1  Bhubaneswar  13.0   6.0
2        Delhi   NaN  23.0
3      Kolkata  30.0   NaN
4       Mumbai  12.0   5.0

In [8]:
df = pd.merge(temp, wind, on='City', how="outer", indicator=True)
df

          City  temp  wind      _merge
0    Bengaluru  19.0   NaN   left_only
1  Bhubaneswar  13.0   6.0        both
2        Delhi   NaN  23.0  right_only
3      Kolkata  30.0   NaN   left_only
4       Mumbai  12.0   5.0        both

In [9]:
df = pd.merge(temp, wind, on='City', how="left", indicator=True)
df

          City  temp  wind     _merge
0       Mumbai    12   5.0       both
1  Bhubaneswar    13   6.0       both
2    Bengaluru    19   NaN  left_only
3      Kolkata    30   NaN  left_only

In [17]:
df = pd.merge(temp, wind, on='City', how="left", suffixes=(False, False))
df

          City  temp  wind
0       Mumbai    12   5.0
1  Bhubaneswar    13   6.0
2    Bengaluru    19   NaN
3      Kolkata    30   NaN

In [22]:
data = {
    'Employee': ['A', 'B', 'C', 'A', 'B', 'C'],
    'Department': ['HR', 'HR', 'HR', 'IT', 'IT', 'IT'],
    'Year': [2022, 2022, 2022, 2023, 2023, 2023],
    'Salary': [40000, 42000, 41000, 45000, 47000, 46000],
    'Bonus': [2000, 2100, 1900, 2500, 2700, 2600]
}

df = pd.DataFrame(data)
df

  Employee Department  Year  Salary  Bonus
0        A         HR  2022   40000   2000
1        B         HR  2022   42000   2100
2        C         HR  2022   41000   1900
3        A         IT  2023   45000   2500
4        B         IT  2023   47000   2700
5        C         IT  2023   46000   2600

In [23]:
pivot_df = df.pivot(index='Employee', columns='Year', values='Salary')
pivot_df

Year       2022   2023
Employee
A         40000  45000
B         42000  47000
C         41000  46000

In [24]:
pivot_table_df = df.pivot_table(
    index='Employee',
    columns='Year',
    values='Salary',
)
pivot_table_df

Year         2022     2023
Employee
A         40000.0  45000.0
B         42000.0  47000.0
C         41000.0  46000.0

In [25]:
pivot_table_df = df.pivot_table(
    index='Employee',
    columns='Year',
    values='Salary',
    aggfunc='sum',     
    fill_value=0,      
    margins=True,    
    margins_name='Total Salary'
)
pivot_table_df

Year            2022    2023  Total Salary
Employee
A              40000   45000         85000
B              42000   47000         89000
C              41000   46000         87000
Total Salary  123000  138000        261000

In [26]:
data = {
    'Employee': ['A', 'B', 'C', 'A', 'B', 'C'],
    'Department': ['HR', 'HR', 'HR', 'IT', 'IT', 'IT'],
    'Year': [2022, 2022, 2022, 2023, 2023, 2023],
    'Salary': [40000, 42000, 41000, 45000, 47000, 46000],
    'Bonus': [2000, 2100, 1900, 2500, 2700, 2600]
}

df = pd.DataFrame(data)
df

  Employee Department  Year  Salary  Bonus
0        A         HR  2022   40000   2000
1        B         HR  2022   42000   2100
2        C         HR  2022   41000   1900
3        A         IT  2023   45000   2500
4        B         IT  2023   47000   2700
5        C         IT  2023   46000   2600

In [30]:
melt_df = pd.melt(
    df,
    id_vars=['Employee', 'Department'],   
    value_vars=['Salary', 'Bonus', 'Year'],       
    var_name='Title',                  
    value_name='Amount'                   
)
melt_df

   Employee Department   Title  Amount
0         A         HR  Salary   40000
1         B         HR  Salary   42000
2         C         HR  Salary   41000
3         A         IT  Salary   45000
4         B         IT  Salary   47000
5         C         IT  Salary   46000
6         A         HR   Bonus    2000
7         B         HR   Bonus    2100
8         C         HR   Bonus    1900
9         A         IT   Bonus    2500
10        B         IT   Bonus    2700
11        C         IT   Bonus    2600
12        A         HR    Year    2022
13        B         HR    Year    2022
14        C         HR    Year    2022
15        A         IT    Year    2023
16        B         IT    Year    2023
17        C         IT    Year    2023

In [42]:
df.rename(columns={'Employee':'Emp Name', 'Salary': 'Sal'}, inplace=True)
df

  Emp Name Department  Year    Sal  Bonus
0        A         HR  2022  40000   2000
1        B         HR  2022  42000   2100
2        C         HR  2022  41000   1900
3        A         IT  2023  45000   2500
4        B         IT  2023  47000   2700
5        C         IT  2023  46000   2600

In [43]:
data = {
    'Employee': ['A','A', 'B', 'C', 'A', 'B', 'C'],
    'Department': ['HR','HR', 'HR', 'HR', 'IT', 'IT', 'IT'],
    'Year': [2022,2022, 2022, 2022, 2023, 2023, 2023],
    'Salary': [40000,40000, 42000, 41000, 45000, 47000, 46000],
    'Bonus': [2000,2000, 2100, 1900, 2500, 2700, 2600]
}
df3 = pd.DataFrame(data)
df3

  Employee Department  Year  Salary  Bonus
0        A         HR  2022   40000   2000
1        A         HR  2022   40000   2000
2        B         HR  2022   42000   2100
3        C         HR  2022   41000   1900
4        A         IT  2023   45000   2500
5        B         IT  2023   47000   2700
6        C         IT  2023   46000   2600

In [47]:
df3.drop_duplicates(inplace=True)
df3

  Employee Department  Year  Salary  Bonus
0        A         HR  2022   40000   2000
2        B         HR  2022   42000   2100
3        C         HR  2022   41000   1900
4        A         IT  2023   45000   2500
5        B         IT  2023   47000   2700
6        C         IT  2023   46000   2600

In [48]:
df.sort_values('Sal', ascending=True, inplace=True)
df

  Emp Name Department  Year    Sal  Bonus
0        A         HR  2022  40000   2000
2        C         HR  2022  41000   1900
1        B         HR  2022  42000   2100
3        A         IT  2023  45000   2500
5        C         IT  2023  46000   2600
4        B         IT  2023  47000   2700